### ISSUE TITLE
chapter 3 failed to build

### ISSUE THREAD

**Issue by z11373** [PacktPublishing/Building-Big-Data-Pipelines-with-Apache-Beam#32]
Hi, if i build from intellij then it complains on all these imports:
```
import com.packtpub.beam.chapter3.RpcServiceGrpc.RpcServiceBlockingStub;
import com.packtpub.beam.chapter3.Service.Request;
import com.packtpub.beam.chapter3.Service.Response;
```

For example, it'd say **java: package com.packtpub.beam.chapter3.RpcServiceGrpc does not exist**

but if i run **mvnw clean install** from command-line, then I'd get this error below, but building beam-util from intellij seems fine, any idea? I am running on Windows with JDK 11, thanks!

```
Jan 28, 2023 2:54:28 PM com.diffplug.spotless.FormatExceptionPolicyLegacy error
SEVERE: Step 'google-java-format' found problem in 'src\main\java\com\packtpub\beam\util\DebugOutput.java':
null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.diffplug.spotless.java.GoogleJavaFormatStep$State.lambda$createFormat$0(GoogleJavaFormatStep.java:134)
        at com.diffplug.spotless.FormatterFunc.apply(FormatterFunc.java:32)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:78)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:212)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:188)
        at com.diffplug.spotless.maven.SpotlessApplyMojo.process(SpotlessApplyMojo.java:45)
        at com.diffplug.spotless.maven.AbstractSpotlessMojo.execute(AbstractSpotlessMojo.java:142)
        at com.diffplug.spotless.maven.AbstractSpotlessMojo.execute(AbstractSpotlessMojo.java:127)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
Caused by: com.google.googlejavaformat.java.FormatterException: 1:3: error: illegal '.'
        at com.google.googlejavaformat.java.FormatterException.fromJavacDiagnostics(FormatterException.java:50)
        at com.google.googlejavaformat.java.Formatter.format(Formatter.java:151)
        at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:258)
        at com.google.googlejavaformat.java.Formatter.formatSource(Formtter.java:234)
        at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:202)
        ... 43 more
       ...
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.893 s
[INFO] Finished at: 2023-01-28T14:54:29-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.0.1:apply (apply) on project beam-util: Execution apply of goal com.diffplug.spotless:spotless-maven-plugin:2.0.1:apply failed: java.lang.reflect.InvocationTargetException: 1:3: error: illegal '.' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :beam-util
```

**Comment by je-ik** [comment]
Do you have a clean checkout of the source? Looks like there might be a syntax error in the `DebugOutput` class.

Regarding Idea, this might be related, the classes that it complains on are generated from `.proto` files during the build. It might help to reload the maven build.

**Comment by z11373** [comment]
Thanks for replying. So I just tried from clean slate again by doing:
- git clone https://github.com/PacktPublishing/Building-Big-Data-Pipelines-with-Apache-Beam.git
- then go to that folder, and run "mvnw clean install", and it gave me the same outcome

do you know how to fix/work around this issue?
```
Feb 18, 2023 10:41:10 AM com.diffplug.spotless.FormatExceptionPolicyLegacy error
SEVERE: Step 'google-java-format' found problem in 'src\main\java\com\packtpub\beam\util\DebugOutput.java':
null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
      ...
```

**Comment by z11373** [comment]
ok, i was able to progress by removing that `google-java-format` plug-in from `pom.xml`, but then it failed on chapter 1, got this error:
```
[ERROR] Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.04 s <<< FAILURE! - in com.packtpub.beam.chapter1.Chapter1DemoTest
[ERROR] com.packtpub.beam.chapter1.Chapter1DemoTest.testFirstPipelineStream  Time elapsed: 0.004 s  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/zaina/github/Building-Big-Data-Pipelines-with-Apache-Beam/chapter1/target/classes/lorem.txt
        at com.packtpub.beam.chapter1.Chapter1DemoTest.<init>(Chapter1DemoTest.java:52)
```

so i re-run again with `-DskipTests=true` and it made progress until error on chapter 6:
```
[INFO] --- exec-maven-plugin:3.0.0:exec (default) @ beam-chapter6 ---
[ERROR] Command execution failed.
java.io.IOException: Cannot run program "\bin\bash" (in directory "C:\Users\zaina\github\Building-Big-Data-Pipelines-with-Apache-Beam\chapter6"): CreateProcess error=2, The system cannot find the file specified
    at java.lang.ProcessBuilder.start (ProcessBuilder.java:1128)
    at java.lang.ProcessBuilder.start (ProcessBuilder.java:1071)
    at java.lang.Runtime.exec (Runtime.java:589)
    ...
```

i wonder if no one is running this project on windows machine?

**Comment by z11373** [comment]
i replaced `/bin/bash` in pom.xml of chapter6 with `C:\Windows\System32\bash.exe` and it ran into some pip install issue on particular dependency. I decided to skip that module `chapter6` for now, and it's all good. I'll revisit that chapter later. Thanks!

**Comment by je-ik** [comment]
Interesting, looks like there is some problem with the google-java-format spotless extension on Windows.

Spotless on my local works well, need to update only the license headers, in #33.

**Comment by je-ik** [comment]
Related https://github.com/PacktPublishing/Building-Big-Data-Pipelines-with-Apache-Beam/pull/18

**Comment by je-ik** [comment]
I merged the PR with several other fixes, that should fix the issue with chapter 6. I'm unable to reproduce the problem with spotless, though.

**Comment by z11373** [comment]
thanks for fixing some of the issues, and yes, i still run into that spotless error, so have to remove that plugin from pom.xml

also, i got test error on chapter 5, you didn't see this error?
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.packtpub.beam.chapter5.SchemaSportTrackerTest
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.881 s <<< FAILURE! - in com.packtpub.beam.chapter5.SchemaSportTrackerTest
[ERROR] com.packtpub.beam.chapter5.SchemaSportTrackerTest.testPipeline  Time elapsed: 3.839 s  <<< ERROR!
org.apache.beam.sdk.Pipeline$PipelineExecutionException:
java.lang.AssertionError: MapElements/Map/ParMultiDo(Anonymous).output:
Expected: iterable with items ["track1:614,257", "track2:5641,1262"] in any order
     but: no item matches: "track1:614,257", "track2:5641,1262" in []
        at com.packtpub.beam.chapter5.SchemaSportTrackerTest.testPipeline(SchemaSportTrackerTest.java:112)
Caused by: java.lang.AssertionError:
MapElements/Map/ParMultiDo(Anonymous).output:
Expected: iterable with items ["track1:614,257", "track2:5641,1262"] in any order
     but: no item matches: "track1:614,257", "track2:5641,1262" in []
        at com.packtpub.beam.chapter5.SchemaSportTrackerTest.testPipeline(SchemaSportTrackerTest.java:108)
Caused by: java.lang.AssertionError:

Expected: iterable with items ["track1:614,257", "track2:5641,1262"] in any order
     but: no item matches: "track1:614,257", "track2:5641,1262" in []
```

**Comment by z11373** [comment]
and building chapter 6 still failed on my machine too, i guess you likely don't see this on your machine:

```
Successfully installed apache-beam-2.43.0 certifi-2022.12.7 charset-normalizer-3.0.1 cloudpickle-2.2.1 crcmod-1.7 deprecation-2.1.0 dill-0.3.1.1 docker-6.0.1 docopt-0.6.2 exceptiongroup-1.1.0 execnet-1.9.0 fastavro-1.7.1 fasteners-0.18 freezegun-1.2.2 greenlet-2.0.2 grpcio-1.40.0 grpcio-tools-1.40.0 hdfs-2.7.0 hypothesis-6.68.2 iniconfig-2.0.0 joblib-1.2.0 mock-2.0.0 numpy-1.22.4 objsize-0.5.2 orjson-3.8.6 parameterized-0.8.1 pbr-5.11.1 pluggy-1.0.0 proto-plus-1.22.2 protobuf-3.19.6 psycopg2-binary-2.9.5 py-1.11.0 pyarrow-9.0.0 pydot-1.4.2 pyhamcrest-1.10.1 pymongo-3.13.0 pymysql-1.0.2 pytest-7.2.1 pytest-forked-1.6.0 pytest-timeout-2.1.0 pytest-xdist-2.5.0 regex-2022.10.31 requests-2.28.2 requests-mock-1.10.0 scikit-learn-1.2.1 scipy-1.10.1 sortedcontainers-2.4.0 sqlalchemy-1.4.46 tenacity-5.1.5 testcontainers-3.7.1 threadpoolctl-3.1.0 tomli-2.0.1 typing-extensions-4.5.0 urllib3-1.26.14 wrapt-1.14.1 zstandard-0.19.0
running build
running build_py
file service_pb2.py (for module service_pb2) not found
file service_pb2_grpc.py (for module service_pb2_grpc) not found
creating build
creating build/lib
copying utils.py -> build/lib
file service_pb2.py (for module service_pb2) not found
file service_pb2_grpc.py (for module service_pb2_grpc) not found
.E...
======================================================================
ERROR: test_rpc_par_do (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_rpc_par_do
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/mnt/c/Users/zaina/github/Building-Big-Data-Pipelines-with-Apache-Beam/chapter6/src/main/python/test_rpc_par_do.py", line 6, in <module>
    import service_pb2
ModuleNotFoundError: No module named 'service_pb2'


----------------------------------------------------------------------
Ran 5 tests in 2.326s

FAILED (errors=1)
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:982)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:929)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:457)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:61)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Building Big Data Pipelines with Apache Beam 1.0.0:
[INFO]
[INFO] Building Big Data Pipelines with Apache Beam ....... SUCCESS [  0.148 s]
[INFO] Building Big Data Pipelines with Apache Beam Utils . SUCCESS [  3.122 s]
[INFO] Building Big Data Pipelines with Apache Beam Chapter 1 SUCCESS [  0.851 s]
[INFO] Building Big Data Pipelines with Apache Beam Chapter 2 SUCCESS [  3.102 s]
[INFO] Building Big Data Pipelines with Apache Beam Chapter 3 SUCCESS [  6.588 s]
[INFO] Building Big Data Pipelines with Apache Beam Chapter 4 SUCCESS [  3.105 s]
[INFO] Building Big Data Pipelines with Apache Beam Chapter 5 SUCCESS [  3.269 s]
[INFO] Building Big Data Pipelines with Apache Beam Chapter 6 FAILURE [05:06 min]
[INFO] Building Big Data Pipelines with Apache Beam Chapter 7 SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:27 min
[INFO] Finished at: 2023-02-20T16:41:44-05:00
[INFO] ------------------------------------------------------------------------
```

**Comment by je-ik** [comment]
Tha latter error might be due to missing compilation of `.proto`, and/or `grpc` service. This works on the github CI with WSL, you might use it as well?
I cannot reproduce the first error (and it also does not happen on the github CI), so this would be harder to resolve.
